/*1.Revising Aggregations - The Sum Function*/
SELECT SUM(POPULATION)
From CITY 
WHERE DISTRICT = 'California';

/*2.Average Population*/
SELECT ROUND(AVG(POPULATION), 0)
From CITY;

/*3.African Cities*/
SELECT CITY.NAME 
FROM CITY 
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE 
WHERE COUNTRY.CONTINENT = 'Africa';

/*4.Average Population of Each Continent*/
SELECT COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION))
FROM CITY
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE
GROUP BY COUNTRY.CONTINENT;

/*5.Placements*/

